export const DomainErrorCode = {
  BUDGET_ALREADY_EXISTS: 'BUDGET_ALREADY_EXISTS',
  BUDGET_NOT_FOUND: 'BUDGET_NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  USER_INVALID_LOGIN_CREDENTIALS: 'USER_INVALID_LOGIN_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_WITH_EMAIL_ALREADY_EXISTS: 'USER_WITH_EMAIL_ALREADY_EXISTS',
}

export type DomainErrorCode = (typeof DomainErrorCode)[keyof typeof DomainErrorCode]
