export const Token = {
  APP: 'APP',
  BUDGETS_REPOSITORY: 'BUDGETS_REPOSITORY',
  BUDGET_FINDER: 'BUDGET_FINDER',
  CLOCK: 'CLOCK',
  CRYPTO: 'CRYPTO',
  DB_CONFIG: 'DB_CONFIG',
  ENDPOINT: 'ENDPOINT',
  FIXED_EXPENSES_REPOSITORY: 'FIXED_EXPENSES_REPOSITORY',
  JWT_DECODER: 'JWT_DECODER',
  JWT_SIGNER: 'JWT_SIGNER',
  LOGGER: 'LOGGER',
  USERS_REPOSITORY: 'USERS_REPOSITORY',
} as const

export type Token = (typeof Token)[keyof typeof Token]
